### ISSUE TITLE
[Forge 43.3.0 1.19.2] Industrial fan crashing server when used with blue seething sail

### ISSUE THREAD

**Issue by PavlychevV** [LopyLuna/Create-Flavored#11]
When a player comes into contact with the fan's smoke, the server crashes.
`Caused by: java.lang.NoClassDefFoundError: com/simibubi/create/content/kinetics/fan/FanProcessing$SplashingWrapper`
full log: https://mclo.gs/rvY3iHz

Log after player join:
```
[20Oct2023 13:09:24.053] [VoiceChatPacketProcessingThread/INFO] [voicechat/]: [voicechat] Successfully authenticated player ee78e302-64be-313d-bd57-27ae191b428a
[20Oct2023 13:09:24.097] [Server thread/INFO] [com.kyanite.paragon.Paragon/]: Handshake response from CommandBlockYTX : SUCCESS
[20Oct2023 13:09:24.098] [Server thread/INFO] [com.kyanite.paragon.Paragon/]: Handshake succeeded with no issues
[20Oct2023 13:09:24.098] [Server thread/INFO] [com.kyanite.paragon.Paragon/]: Handshake response from CommandBlockYTX : SUCCESS
[20Oct2023 13:09:24.098] [Server thread/INFO] [com.kyanite.paragon.Paragon/]: Handshake succeeded with no issues
[20Oct2023 13:09:24.127] [Netty Epoll Server IO #3/INFO] [simplelogin/]: Player commandblockytx has successfully logged in.
[20Oct2023 13:09:24.518] [Server thread/WARN] [PlayerAbilityLib/]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
java.lang.RuntimeException: stacktrace
	at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:61) ~[PlayerAbilityLib-forge-b2d633b0ae.jar%23606!/:?]
	at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[PlayerAbilityLib-forge-b2d633b0ae.jar%23606!/:?]
	at net.minecraft.server.level.ServerPlayer.handler$zdh000$checkAbilityConsistency(ServerPlayer.java:1814) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.level.ServerPlayer.m_6885_(ServerPlayer.java:1206) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at com.vice.balancedflight.content.flightAnchor.FlightController.startFlying(FlightController.java:44) ~[balancedflight-1.19.2_v2.1.0.jar%23341!/:1.19.2_v2.1.0]
	at com.vice.balancedflight.content.flightAnchor.FlightController.tick(FlightController.java:32) ~[balancedflight-1.19.2_v2.1.0.jar%23341!/:1.19.2_v2.1.0]
	at com.vice.balancedflight.foundation.events.CommonEvents.onPlayerTick(CommonEvents.java:22) ~[balancedflight-1.19.2_v2.1.0.jar%23341!/:1.19.2_v2.1.0]
	at com.vice.balancedflight.foundation.events.__CommonEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[balancedflight-1.19.2_v2.1.0.jar%23341!/:1.19.2_v2.1.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:814) ~[forge-1.19.2-43.3.0-universal.jar%23532!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:216) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20Oct2023 13:09:24.674] [Server thread/WARN] [PlayerAbilityLib/]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
java.lang.RuntimeException: stacktrace
	at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:61) ~[PlayerAbilityLib-forge-b2d633b0ae.jar%23606!/:?]
	at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[PlayerAbilityLib-forge-b2d633b0ae.jar%23606!/:?]
	at net.minecraft.server.level.ServerPlayer.handler$zdh000$checkAbilityConsistency(ServerPlayer.java:1814) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.level.ServerPlayer.m_6885_(ServerPlayer.java:1206) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at com.vice.balancedflight.content.flightAnchor.FlightController.startFlying(FlightController.java:44) ~[balancedflight-1.19.2_v2.1.0.jar%23341!/:1.19.2_v2.1.0]
	at com.vice.balancedflight.content.flightAnchor.FlightController.tick(FlightController.java:32) ~[balancedflight-1.19.2_v2.1.0.jar%23341!/:1.19.2_v2.1.0]
	at com.vice.balancedflight.foundation.events.CommonEvents.onPlayerTick(CommonEvents.java:22) ~[balancedflight-1.19.2_v2.1.0.jar%23341!/:1.19.2_v2.1.0]
	at com.vice.balancedflight.foundation.events.__CommonEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[balancedflight-1.19.2_v2.1.0.jar%23341!/:1.19.2_v2.1.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:814) ~[forge-1.19.2-43.3.0-universal.jar%23532!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:216) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20Oct2023 13:09:24.996] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/simibubi/create/content/kinetics/fan/FanProcessing$SplashingWrapper
	at uwu.lopyluna.create_dd.recipes.BakingFanProcessing.<clinit>(BakingFanProcessing.java:69) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at uwu.lopyluna.create_dd.recipes.BakingFanProcessing$FanType$5.affectEntity(BakingFanProcessing.java:476) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at uwu.lopyluna.create_dd.block.BlockProperties.bronze_encased_fan.BronzeAirCurrent.tickAffectedEntities(BronzeAirCurrent.java:132) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at uwu.lopyluna.create_dd.block.BlockProperties.bronze_encased_fan.BronzeAirCurrent.tick(BronzeAirCurrent.java:78) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at uwu.lopyluna.create_dd.block.BlockProperties.bronze_encased_fan.BronzeEncasedFanBlockEntity.tick(BronzeEncasedFanBlockEntity.java:223) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.m_155252_(SmartBlockEntityTicker.java:15) ~[create-1.19.2-0.5.1.e.jar%23361!/:0.5.1.e]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.simibubi.create.content.kinetics.fan.FanProcessing$SplashingWrapper
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at uwu.lopyluna.create_dd.recipes.BakingFanProcessing.<clinit>(BakingFanProcessing.java:69) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at uwu.lopyluna.create_dd.recipes.BakingFanProcessing$FanType$5.affectEntity(BakingFanProcessing.java:476) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at uwu.lopyluna.create_dd.block.BlockProperties.bronze_encased_fan.BronzeAirCurrent.tickAffectedEntities(BronzeAirCurrent.java:132) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at uwu.lopyluna.create_dd.block.BlockProperties.bronze_encased_fan.BronzeAirCurrent.tick(BronzeAirCurrent.java:78) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at uwu.lopyluna.create_dd.block.BlockProperties.bronze_encased_fan.BronzeEncasedFanBlockEntity.tick(BronzeEncasedFanBlockEntity.java:223) ~[Create-Dreams-n-Desires-1.19.2-0.1a.PREBETA.jar%23363!/:0.1a.PREBETA]
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.m_155252_(SmartBlockEntityTicker.java:15) ~[create-1.19.2-0.5.1.e.jar%23361!/:0.5.1.e]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23527!/:?]
	... 5 more
[20Oct2023 13:09:25.021] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 974c9e17-af43-427f-a4fd-8ca275ee625f
[20Oct2023 13:09:25.037] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /home/vladislav/minecraft/bebra_forge/./crash-reports/crash-2023-10-20_13.09.25-server.txt
[20Oct2023 13:09:25.038] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[20Oct2023 13:09:25.038] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[20Oct2023 13:09:25.040] [Physics thread/WARN] [org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineBackgroundTask/]: Physics pipeline ending
[20Oct2023 13:09:25.050] [VoiceChatPacketProcessingThread/INFO] [voicechat/]: [voicechat] Successfully validated connection of player ee78e302-64be-313d-bd57-27ae191b428a
[20Oct2023 13:09:25.054] [VoiceChatPacketProcessingThread/INFO] [voicechat/]: [voicechat] Player CommandBlockYTX (ee78e302-64be-313d-bd57-27ae191b428a) successfully connected to voice chat
[20Oct2023 13:09:25.213] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: CommandBlockYTX lost connection: Server closed
[20Oct2023 13:09:25.213] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: CommandBlockYTX left the game
[20Oct2023 13:09:25.219] [Server thread/INFO] [voicechat/]: [voicechat] Disconnecting client CommandBlockYTX
[20Oct2023 13:09:25.369] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[20Oct2023 13:09:28.163] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[20Oct2023 13:09:28.774] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:glacio
[20Oct2023 13:09:28.776] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:moon
[20Oct2023 13:09:28.778] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/create_dd:ponder
[20Oct2023 13:09:28.778] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[20Oct2023 13:09:28.779] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:venus
[20Oct2023 13:09:28.781] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[20Oct2023 13:09:28.818] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:venus_orbit
[20Oct2023 13:09:28.820] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:moon_orbit
[20Oct2023 13:09:28.822] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:mars
[20Oct2023 13:09:28.824] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/deeperdarker:otherside
[20Oct2023 13:09:28.826] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:earth_orbit
[20Oct2023 13:09:28.827] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:glacio_orbit
[20Oct2023 13:09:28.829] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/aether:the_aether
[20Oct2023 13:09:28.831] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:mercury_orbit
[20Oct2023 13:09:28.833] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/twilightforest:twilight_forest
[20Oct2023 13:09:28.838] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:mars_orbit
[20Oct2023 13:09:28.840] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ad_astra:mercury
[20Oct2023 13:09:28.842] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ae2:spatial_storage
[20Oct2023 13:09:28.970] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (glacio): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (moon): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (ponder): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (venus): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (venus_orbit): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (moon_orbit): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mars): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (otherside): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (earth_orbit): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (glacio_orbit): All chunks are saved
[20Oct2023 13:09:28.971] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (the_aether): All chunks are saved
[20Oct2023 13:09:28.972] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mercury_orbit): All chunks are saved
[20Oct2023 13:09:28.972] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[20Oct2023 13:09:28.972] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mars_orbit): All chunks are saved
[20Oct2023 13:09:28.972] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mercury): All chunks are saved
[20Oct2023 13:09:28.972] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[20Oct2023 13:09:28.972] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[20Oct2023 13:09:29.033] [Server thread/INFO] [simplelogin/]: Shutting down player login handler
[20Oct2023 13:09:29.033] [Server thread/INFO] [simplelogin/]: Disabling all plugins
[20Oct2023 13:09:29.034] [Server thread/INFO] [simplelogin/]: Saving all entries
[20Oct2023 13:09:29.035] [Server thread/INFO] [Framework/]: Unloading server configs...
[20Oct2023 13:09:29.036] [Server thread/INFO] [configured/]: Unloading server configs...
[20Oct2023 13:09:29.036] [Server thread/INFO] [configured/]: Sending config unload event for configured.developer.toml
```

**Comment by LopyLuna** [comment]
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/100169742/004a0a5a-4329-4ce5-843e-fa9cb8159d13)
its a known issue
