### ISSUE TITLE
Bug/Error in Dreams & Desires 1.19.2 1.2c.Snapshot Mid-Dev (ExcavationDrill). Unable to play on server

### ISSUE THREAD

**Issue by Talandar99** [LopyLuna/Create-Flavored#113]
#### Context:
Hi. I have created modpack to play with my friends, and wanted to update mods including Dreams And Desires. I am using primarly modrinth for getting my mods

#### Versions
- Minecraft 1.19.2
- Forge 43.4.4
- Create 1.19.2-0.5.1.i
- Create: Dreams & Desires 1.19.2 1.2c.Snapshot Mid-Dev

#### Issue
- I am able to break the blok, but nothing drops
- After trying to get into breaked block, character glitches sugesting that block still exist
- `uwu.lopyluna.create_dd.content.items.equipment.excavation_drill.__ExcavationDrillItem_onBlockDestroyed_BreakEvent.` suggest that it is caused by dreams and desire so I created this issue 
- serverlog in moment of breaking block is bellow
- version `Create: Dreams & Desires 1.19.2 0.1c.Release-Early-Dev` do not have this error/bug so i think i will stay on this one for a while

```java
mc-1  | [21:06:02] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@3d358b89, suppressing error
mc-1  | java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
mc-1  |         at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.4.4.jar%2367!/:1.0]
mc-1  |         at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?]
mc-1  |         at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?]
mc-1  |         at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?]
mc-1  |         at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
mc-1  |         at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
mc-1  |         at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
mc-1  |         at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
mc-1  |         at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
mc-1  |         at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
mc-1  |         at net.minecraftforge.network.simple.SimpleChannel.sendToServer(SimpleChannel.java:87) ~[forge-1.19.2-43.4.4-universal.jar%23478!/:?]
mc-1  |         at uwu.lopyluna.create_dd.content.items.equipment.excavation_drill.ExcavationDrillItem.onBlockDestroyed(ExcavationDrillItem.java:109) ~[Create-DnDesire-1.19.2-1.2c.Beta%2520Mid-Dev.jar%23332!/:1.2c.Beta Mid-Dev]
mc-1  |         at uwu.lopyluna.create_dd.content.items.equipment.excavation_drill.__ExcavationDrillItem_onBlockDestroyed_BreakEvent.invoke(.dynamic) ~[Create-DnDesire-1.19.2-1.2c.Beta%2520Mid-Dev.jar%23332!/:1.2c.Beta Mid-Dev]
mc-1  |         at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
mc-1  |         at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
mc-1  |         at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
mc-1  |         at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:633) ~[forge-1.19.2-43.4.4-universal.jar%23478!/:?]
mc-1  |         at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:229) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.level.ServerPlayerGameMode.m_215116_(ServerPlayerGameMode.java:218) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:188) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1024) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23473!/:?]
mc-1  |         at java.lang.Thread.run(Thread.java:842) [?:?]
```

**Comment by Tigertycoon** [comment]
I Second this error. Exact same Situation. Will Downgrade as well for now.

**Comment by akincan-kilic** [comment]
I'm also experiencing this error. Downgrading to `1.19.2 0.1c.Release-Early-Dev` has fixed it.

**Comment by LopyLuna** [comment]
1.19.2 isnt supported anymore
