### ISSUE TITLE
Excavation drill not working on dedicated servers

### ISSUE THREAD

**Issue by 0xadg** [LopyLuna/Create-Flavored#48]
As title says, Excavation drill doesn't work on dedicated server, throwing a `Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket` error when trying to break a block.
Mod version is **0.2.5b-PREBETA**;
Game version is **1.19.2**;

Full error message:
`[Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@143755bd, suppressing error
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.3.8.jar%2367!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
        at uwu.lopyluna.create_dd.item.ItemProperties.drilltool.ExcavationDrillItem.m_8102_(ExcavationDrillItem.java:47) ~[Create-Dreams-n-Desires-1.19.2-0.2.5b.PREBETA.jar%23181!/:0.2.5b.PREBETA] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.item.ItemStack.m_41691_(ItemStack.java:262) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,xf:fml:improvableskills:ItemStackHurtHook,xf:fml:forge:itemstack,re:classloading,xf:fml:improvableskills:ItemStackHurtHook,xf:fml:forge:itemstack,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:extendedgears-common.mixins.json:MixinItemStack,pl:mixin:A}
        at net.minecraft.world.entity.player.Inventory.m_36020_(Inventory.java:387) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,re:classloading,pl:mixin:APP:carryon.mixins.json:InventoryMixin,pl:mixin:A}
        at net.minecraft.world.entity.player.Player.getDigSpeed(Player.java:693) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:createbigcannons-common.mixins.json:PlayerMixin,pl:mixin:APP:immersive_aircraft.mixins.json:PlayerEntityMixin,pl:mixin:APP:epicfight.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A}
        at net.minecraft.world.level.block.state.BlockBehaviour.m_5880_(BlockBehaviour.java:365) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways-common.mixins.json:MixinBlockBehaviour,pl:mixin:APP:chipped.mixins.json:BlockBehaviourMixin,pl:mixin:A}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60625_(BlockBehaviour.java:574) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:161) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.artifacts.json:item.diggingclaws.ServerPlayerGameModeMixin,pl:mixin:APP:mixins.improvableskills.json:ServerPlayerGameModeMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1024) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) [?:?] {}`

Also, a list of other mods installed on the server:
• mods_folder createbigcannons-forge-1.19.2-0.5.3.b.jar : createbigcannons (0.5.3.b-nightly-4ab94a1) - 1
• mods_folder netherportalfix-forge-1.19-10.0.1.jar : netherportalfix (10.0.1) - 1
• mods_folder AdvancedPeripherals-1.19.2-0.7.35r.jar : advancedperipherals (0.7.35r) - 1
• mods_folder Create-Dreams-n-Desires-1.19.2-0.2.5b.PREBETA.jar : create_dd (0.2.5b.PREBETA) - 1
• mods_folder botarium-forge-1.19.2-1.9.2.jar : botarium (1.9.2) - 1
• mods_folder jei-1.19.2-forge-11.6.0.1019.jar : jei (11.6.0.1019) - 1
• mods_folder HammerLib-1.19.2-19.3.76.jar : hammerlib (19.3.76) - 1
• mods_folder goblintraders-1.8.0-1.19.2.jar : goblintraders (1.8.0) - 1
• mods_folder immersive_aircraft-0.7.51.19.2-forge.jar : immersive_aircraft (0.7.5+1.19.2) - 1
• mods_folder sophisticatedcore-1.19.2-0.6.4.587.jar : sophisticatedcore (1.19.2-0.6.4.587) - 1
• mods_folder rubidium-mc1.19.2-0.6.2c.jar : rubidium (0.6.2c) - 1
• mods_folder create_recycle_1.0.2_forge_1.19.2.jar : create_crush_everything (1.0.2) - 1
• mods_folder waystones-forge-1.19.2-11.4.2.jar : waystones (11.4.2) - 1
• mods_folder villagernames-1.19.2-7.3.jar : villagernames (7.3) - 1
• mods_folder EpicFight-19.5.24.jar : epicfight (19.5.24) - 1
• JarInJar ritchiesprojectilelib-1.0.0-40ef15b+1.19.2-forge.jar : ritchiesprojectilelib (1.0.0-40ef15b+1.19.2-forge) - 1
• mods_folder journeymap-1.19.2-5.9.8-forge.jar : journeymap (5.9.8) - 1
• mods_folder CTM-1.19.2-1.1.6+8.jar : ctm (1.19.2-1.1.6+8) - 1
• mods_folder citadel-2.1.4-1.19.jar : citadel (2.1.4) - 1
• mods_folder artifacts-1.19.2-5.0.5.jar : artifacts (1.19.2-5.0.5) - 1
• mods_folder badpackets-forge-0.2.3.jar : badpackets (0.2.3) - 1
• JarInJar mixinextras-forge-0.2.0-beta.6.jar : mixinextras (0.2.0-beta.6) - 1
• mods_folder sophisticatedbackpacks-1.19.2-3.20.2.1035.jar : sophisticatedbackpacks (1.19.2-3.20.2.1035) - 1
• JarInJar create_dragon_lib-1.19.2-1.4.2.jar : create_dragon_lib (1.4.2) - 1
• mods_folder createdieselgenerators-1.19.2-1.2h.jar : createdieselgenerators (1.19.2-1.2h) - 1
• mods_folder Steam_Rails-1.6.1+forge-mc1.19.2.jar : railways (1.6.1+forge-mc1.19.2) - 1
• mods_folder create-new-age-forge-1.19.2-1.1.2.jar : create_new_age (1.1.2) - 1
• mods_folder catalogue-1.7.0-1.19.2.jar : catalogue (1.7.0) - 1
• mods_folder balm-forge-1.19.2-4.6.0.jar : balm (4.6.0) - 1
• mods_folder carryon-forge-1.19.2-2.1.2.23.jar : carryon (2.1.2.23) - 1
• mods_folder JustEnoughResources-1.19.2-1.2.3.243.jar : jeresources (1.2.3.243) - 1
• mods_folder create_creative-1.19.2-0.1.0.jar : create_creative (0.1.0) - 1
• mods_folder ImmersivePetroleum-1.19.2-4.2.0-28.jar : immersivepetroleum (4.2.0-28) - 1
• mods_folder cloth-config-8.3.115-forge.jar : cloth_config (8.3.115) - 1
• minecraft forge-1.19.2-43.3.8-universal.jar : forge (43.3.8) - 1
• mods_folder ImmersivePosts-1.19.2-4.3.0-8.jar : immersiveposts (4.3.0-8) - 1
• mods_folder corpse-forge-1.19.2-1.0.12.jar : corpse (1.19.2-1.0.12) - 1
• mods_folder chipped-forge-1.19.2-2.1.5.jar : chipped (2.1.5) - 1
• minecraft server-1.19.2-20220805.130853-srg.jar : minecraft (1.19.2) - 1
• mods_folder FarmersDelight-1.19.2-1.2.4.jar : farmersdelight (1.19.2-1.2.4) - 1
• mods_folder TerraBlender-forge-1.19.2-2.0.1.166.jar : terrablender (2.0.1.166) - 1
• mods_folder ImmersiveEngineering-1.19.2-9.2.4-170.jar : immersiveengineering (1.19.2-9.2.4-170) - 1
• mods_folder BiomesOPlenty-1.19.2-17.1.2.544.jar : biomesoplenty (17.1.2.544) - 1
• mods_folder Jade-1.19.1-forge-8.9.2.jar : jade (8.9.2) - 1
• mods_folder explorify-forge-1.19-1.3.0.jar : explorify (1.19-1.3.0) - 1
• JarInJar kffmod-3.12.0.jar : kotlinforforge (3.12.0) - 1
• mods_folder ImprovableSkills-1.19.2-19.2.9.jar : improvableskills (19.2.9) - 1
• mods_folder easy-villagers-forge-1.19.2-1.1.4.jar : easy_villagers (1.19.2-1.1.4) - 1
• mods_folder curios-forge-1.19.2-5.1.6.1.jar : curios (1.19.2-5.1.6.1) - 1
• mods_folder archaeology-api-1.19.2-1.0.0.jar : archaeology (1.0.0) - 1
• JarInJar flywheel-forge-1.19.2-0.6.10-20.jar : flywheel (0.6.10-20) - 1
• mods_folder create-1.19.2-0.5.1.f.jar : create (0.5.1.f) - 1
• mods_folder createdeco-1.3.3-1.19.2.jar : createdeco (1.3.3-1.19.2) - 1
• mods_folder interiors-0.5.3+forge-mc1.19.2.jar : interiors (0.5.3) - 1
• mods_folder create-stuff-additions1.19.2_v2.0.4a.jar : create_sa (2.0.4.) - 1
• mods_folder collective-1.19.2-7.40.jar : collective (7.40) - 1
• mods_folder JustEnoughProfessions-forge-1.19.2-2.0.2.jar : justenoughprofessions (2.0.2) - 1
• mods_folder resourcefullib-forge-1.19.2-1.1.24.jar : resourcefullib (1.1.24) - 1
• mods_folder extendedgears-2.1.1-1.19.2-0.5.1.f-forge.jar : extendedgears (2.1.1-1.19.2-0.5.1.f-forge) - 1
• mods_folder architectury-6.6.92-forge.jar : architectury (6.6.92) - 1
• mods_folder ftb-library-forge-1902.4.1-build.236.jar : ftblibrary (1902.4.1-build.236) - 1
• mods_folder item-filters-forge-1902.2.9-build.51.jar : itemfilters (1902.2.9-build.51) - 1
• mods_folder ftb-teams-forge-1902.2.14-build.123.jar : ftbteams (1902.2.14-build.123) - 1
• mods_folder ftb-quests-forge-1902.5.8-build.345.jar : ftbquests (1902.5.8-build.345) - 1
• mods_folder lootr-forge-1.19-0.4.27.71.jar : lootr (0.4.26.69) - 1
• mods_folder cc-tweaked-1.19.2-1.101.4.jar : computercraft (1.101.4) - 1
• mods_folder framework-forge-1.19.2-0.6.16.jar : framework (0.6.16) - 1
• mods_folder FastLeafDecay-30.jar : fastleafdecay (30) - 1
• mods_folder CosmeticArmorReworked-1.19.2-v1a.jar : cosmeticarmorreworked (1.19.2-v1a) - 1
• JarInJar expandability-forge-7.0.0.jar : expandability (7.0.0) - 1
• mods_folder create_enchantment_industry-1.19.2-for-create-0.5.1.f-1.2.9.b.jar : create_enchantment_industry (1.2.9.b) - 1
• mods_folder createaddition-1.19.2-1.2.3.jar : createaddition (1.19.2-1.2.3) - 1

**Comment by LopyLuna** [comment]
known issue but mod is getting rewrite
