### ISSUE TITLE
Server crashed unexpectedly

### ISSUE THREAD

**Issue by Sevelar** [LopyLuna/Create-Flavored#86]
**Version**
Mod Version: 0.1d-Fabric, Minecraft version: 1.20.1, Modloader: Fabric v0.15.11

**Description**
We are playing on relatively large modpack, but crash.log pointed out at create_dd exactly these methods:
```
	at io.github.fabricators_of_create.porting_lib.fluids.wrapper.MergingFluidAttributeFluidType.<init>(MergingFluidAttributeFluidType.java:37)
	at net.minecraft.class_3611.getFluidType(class_3611.java:1525)
	at uwu.lopyluna.create_dd.utils.FluidInteractionRegistry.fluidTypeOf(FluidInteractionRegistry.java:85)
	at uwu.lopyluna.create_dd.utils.FluidInteractionRegistry.getInteractionType(FluidInteractionRegistry.java:38)
	at uwu.lopyluna.create_dd.utils.FluidInteractionRegistry.getFluidInteraction(FluidInteractionRegistry.java:60)
	at net.minecraft.class_3609.handler$bjl000$create_dd$onFluidInteraction(class_3609.java:1085)
```

The server crashed with exception: `java.lang.Error: Watchdog`. It happened suddenly, so I cannot really provide the steps to reproduce this issue.

I'm including the crash log for full info:
[crash-2024-07-29_21.41.36-server.txt](https://github.com/user-attachments/files/16419454/crash-2024-07-29_21.41.36-server.txt)

**Comment by LopyLuna** [comment]
fabric versions is not maintain by me but the community instead
